CC = gcc
CFLAGS = -Wall
SDL_INCLUDE = -IC:\c\include\SDL
SLD_LIBRARY = -LC:\c\lib64
SDL_LINKER_FLAGS = -lSDL2main -lSDL2

icthelight.exe: icthelight.c
	$(CC) $(CFLAGS) $? -o $@

sdlskeleton.exe: sdlskeleton.c
	$(CC) $(CFLAGS) $(SDL_INCLUDE) $(SDL_LIBRARY) $(SDL_LINKER_FLAGS) $? -o $@
