CC = gcc
CFLAGS = -Wall --std=c99 #-fdiagnostics-color
INCLUDE_CURRENT =  -I.
SDL_INCLUDE = -IC:\c\include\SDL
SDL_LIBRARY = -LC:\c\lib64
SDL_LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2
# ??
NO_CONSOLE =# -mwindows

icthelight: main.c icthelight.c color.c common.c complex.c distance.c icthelight.c logging.c plot.c ppm.c quaternion.c vector.c fake_sdl.c
	ctags *.c *.h
	$(CC) $(CFLAGS) $(INCLUDE_CURRENT) $(SDL_LIBRARY) $? $(SDL_LINKER_FLAGS) $(NO_CONSOLE) $(SDL_INCLUDE) -o $@

test: test.c
	$(CC) $? $(CFLAGS) $(SDL_LIBRARY) $(NO_CONSOLE) $(SDL_INCLUDE) $(SDL_LINKER_FLAGS) -o $@

convert:
	mogrify -format png ../output/*.ppm
	del ..\output\*.ppm > nul 2> null

#for the windows users in the crowd
cp:
	chcp 65001

clean:
	del *.exe /q 2> nul
	del TEST_PPM.ppm 2> nul
	del tags 2> nul
	del log\* /q 2> nul
