//License: http://creativecommons.org/publicdomain/zero/1.0/
//adapted from: https://xkcd.com/color/rgb.txt
//several colors were defined twice once spaces and slashes
//were replaced with underscores
//those lines have simply been commented out
//the most useful ones like COLOR_BLACK and COLOR_BLUE are at the bottom of
//the file for some reason. ask randall. idk
#define COLOR_CLOUDY_BLUE                0xacc2d9
#define COLOR_DARK_PASTEL_GREEN          0x56ae57
#define COLOR_DUST                       0xb2996e
#define COLOR_ELECTRIC_LIME              0xa8ff04
#define COLOR_FRESH_GREEN                0x69d84f
#define COLOR_LIGHT_EGGPLANT             0x894585
#define COLOR_NASTY_GREEN                0x70b23f
#define COLOR_REALLY_LIGHT_BLUE          0xd4ffff
#define COLOR_TEA                        0x65ab7c
#define COLOR_WARM_PURPLE                0x952e8f
#define COLOR_YELLOWISH_TAN              0xfcfc81
#define COLOR_CEMENT                     0xa5a391
#define COLOR_DARK_GRASS_GREEN           0x388004
#define COLOR_DUSTY_TEAL                 0x4c9085
#define COLOR_GREY_TEAL                  0x5e9b8a
#define COLOR_MACARONI_AND_CHEESE        0xefb435
#define COLOR_PINKISH_TAN                0xd99b82
#define COLOR_SPRUCE                     0x0a5f38
#define COLOR_STRONG_BLUE                0x0c06f7
#define COLOR_TOXIC_GREEN                0x61de2a
#define COLOR_WINDOWS_BLUE               0x3778bf
#define COLOR_BLUE_BLUE                  0x2242c7
#define COLOR_BLUE_WITH_A_HINT_OF_PURPLE 0x533cc6
#define COLOR_BOOGER                     0x9bb53c
#define COLOR_BRIGHT_SEA_GREEN           0x05ffa6
#define COLOR_DARK_GREEN_BLUE            0x1f6357
#define COLOR_DEEP_TURQUOISE             0x017374
#define COLOR_GREEN_TEAL                 0x0cb577
#define COLOR_STRONG_PINK                0xff0789
#define COLOR_BLAND                      0xafa88b
#define COLOR_DEEP_AQUA                  0x08787f
#define COLOR_LAVENDER_PINK              0xdd85d7
#define COLOR_LIGHT_MOSS_GREEN           0xa6c875
#define COLOR_LIGHT_SEAFOAM_GREEN        0xa7ffb5
#define COLOR_OLIVE_YELLOW               0xc2b709
#define COLOR_PIG_PINK                   0xe78ea5
#define COLOR_DEEP_LILAC                 0x966ebd
#define COLOR_DESERT                     0xccad60
#define COLOR_DUSTY_LAVENDER             0xac86a8
#define COLOR_PURPLEY_GREY               0x947e94
#define COLOR_PURPLY                     0x983fb2
#define COLOR_CANDY_PINK                 0xff63e9
#define COLOR_LIGHT_PASTEL_GREEN         0xb2fba5
#define COLOR_BORING_GREEN               0x63b365
#define COLOR_KIWI_GREEN                 0x8ee53f
#define COLOR_LIGHT_GREY_GREEN           0xb7e1a1
#define COLOR_ORANGE_PINK                0xff6f52
#define COLOR_TEA_GREEN                  0xbdf8a3
#define COLOR_VERY_LIGHT_BROWN           0xd3b683
#define COLOR_EGG_SHELL                  0xfffcc4
#define COLOR_EGGPLANT_PURPLE            0x430541
#define COLOR_POWDER_PINK                0xffb2d0
#define COLOR_REDDISH_GREY               0x997570
#define COLOR_BABY_SHIT_BROWN            0xad900d
#define COLOR_LILIAC                     0xc48efd
#define COLOR_STORMY_BLUE                0x507b9c
#define COLOR_UGLY_BROWN                 0x7d7103
#define COLOR_CUSTARD                    0xfffd78
#define COLOR_DARKISH_PINK               0xda467d
#define COLOR_DEEP_BROWN                 0x410200
#define COLOR_GREENISH_BEIGE             0xc9d179
#define COLOR_MANILLA                    0xfffa86
#define COLOR_OFF_BLUE                   0x5684ae
#define COLOR_BATTLESHIP_GREY            0x6b7c85
#define COLOR_BROWNY_GREEN               0x6f6c0a
#define COLOR_BRUISE                     0x7e4071
#define COLOR_KELLEY_GREEN               0x009337
#define COLOR_SICKLY_YELLOW              0xd0e429
#define COLOR_SUNNY_YELLOW               0xfff917
#define COLOR_AZUL                       0x1d5dec
#define COLOR_DARKGREEN                  0x054907
#define COLOR_GREEN_YELLOW               0xb5ce08
#define COLOR_LICHEN                     0x8fb67b
#define COLOR_LIGHT_LIGHT_GREEN          0xc8ffb0
#define COLOR_PALE_GOLD                  0xfdde6c
#define COLOR_SUN_YELLOW                 0xffdf22
#define COLOR_TAN_GREEN                  0xa9be70
#define COLOR_BURPLE                     0x6832e3
#define COLOR_BUTTERSCOTCH               0xfdb147
#define COLOR_TOUPE                      0xc7ac7d
#define COLOR_DARK_CREAM                 0xfff39a
#define COLOR_INDIAN_RED                 0x850e04
#define COLOR_LIGHT_LAVENDAR             0xefc0fe
#define COLOR_POISON_GREEN               0x40fd14
#define COLOR_BABY_PUKE_GREEN            0xb6c406
#define COLOR_BRIGHT_YELLOW_GREEN        0x9dff00
#define COLOR_CHARCOAL_GREY              0x3c4142
#define COLOR_SQUASH                     0xf2ab15
#define COLOR_CINNAMON                   0xac4f06
#define COLOR_LIGHT_PEA_GREEN            0xc4fe82
#define COLOR_RADIOACTIVE_GREEN          0x2cfa1f
#define COLOR_RAW_SIENNA                 0x9a6200
#define COLOR_BABY_PURPLE                0xca9bf7
#define COLOR_COCOA                      0x875f42
#define COLOR_LIGHT_ROYAL_BLUE           0x3a2efe
#define COLOR_ORANGEISH                  0xfd8d49
#define COLOR_RUST_BROWN                 0x8b3103
#define COLOR_SAND_BROWN                 0xcba560
#define COLOR_SWAMP                      0x698339
#define COLOR_TEALISH_GREEN              0x0cdc73
#define COLOR_BURNT_SIENA                0xb75203
#define COLOR_CAMO                       0x7f8f4e
#define COLOR_DUSK_BLUE                  0x26538d
#define COLOR_FERN                       0x63a950
#define COLOR_OLD_ROSE                   0xc87f89
#define COLOR_PALE_LIGHT_GREEN           0xb1fc99
#define COLOR_PEACHY_PINK                0xff9a8a
#define COLOR_ROSY_PINK                  0xf6688e
#define COLOR_LIGHT_BLUISH_GREEN         0x76fda8
#define COLOR_LIGHT_BRIGHT_GREEN         0x53fe5c
#define COLOR_LIGHT_NEON_GREEN           0x4efd54
#define COLOR_LIGHT_SEAFOAM              0xa0febf
#define COLOR_TIFFANY_BLUE               0x7bf2da
#define COLOR_WASHED_OUT_GREEN           0xbcf5a6
#define COLOR_BROWNY_ORANGE              0xca6b02
#define COLOR_NICE_BLUE                  0x107ab0
#define COLOR_SAPPHIRE                   0x2138ab
#define COLOR_GREYISH_TEAL               0x719f91
#define COLOR_ORANGEY_YELLOW             0xfdb915
#define COLOR_PARCHMENT                  0xfefcaf
#define COLOR_STRAW                      0xfcf679
#define COLOR_VERY_DARK_BROWN            0x1d0200
#define COLOR_TERRACOTA                  0xcb6843
#define COLOR_UGLY_BLUE                  0x31668a
#define COLOR_CLEAR_BLUE                 0x247afd
#define COLOR_CREME                      0xffffb6
#define COLOR_FOAM_GREEN                 0x90fda9
//#define COLOR_GREY_GREEN               0x86a17d
#define COLOR_LIGHT_GOLD                 0xfddc5c
#define COLOR_SEAFOAM_BLUE               0x78d1b6
#define COLOR_TOPAZ                      0x13bbaf
#define COLOR_VIOLET_PINK                0xfb5ffc
#define COLOR_WINTERGREEN                0x20f986
#define COLOR_YELLOW_TAN                 0xffe36e
#define COLOR_DARK_FUCHSIA               0x9d0759
#define COLOR_INDIGO_BLUE                0x3a18b1
#define COLOR_LIGHT_YELLOWISH_GREEN      0xc2ff89
#define COLOR_PALE_MAGENTA               0xd767ad
#define COLOR_RICH_PURPLE                0x720058
#define COLOR_SUNFLOWER_YELLOW           0xffda03
#define COLOR_GREEN_BLUE                 0x01c08d
#define COLOR_LEATHER                    0xac7434
#define COLOR_RACING_GREEN               0x014600
#define COLOR_VIVID_PURPLE               0x9900fa
#define COLOR_DARK_ROYAL_BLUE            0x02066f
#define COLOR_HAZEL                      0x8e7618
#define COLOR_MUTED_PINK                 0xd1768f
#define COLOR_BOOGER_GREEN               0x96b403
#define COLOR_CANARY                     0xfdff63
#define COLOR_COOL_GREY                  0x95a3a6
#define COLOR_DARK_TAUPE                 0x7f684e
#define COLOR_DARKISH_PURPLE             0x751973
#define COLOR_TRUE_GREEN                 0x089404
#define COLOR_CORAL_PINK                 0xff6163
#define COLOR_DARK_SAGE                  0x598556
#define COLOR_DARK_SLATE_BLUE            0x214761
#define COLOR_FLAT_BLUE                  0x3c73a8
#define COLOR_MUSHROOM                   0xba9e88
#define COLOR_RICH_BLUE                  0x021bf9
#define COLOR_DIRTY_PURPLE               0x734a65
#define COLOR_GREENBLUE                  0x23c48b
#define COLOR_ICKY_GREEN                 0x8fae22
#define COLOR_LIGHT_KHAKI                0xe6f2a2
#define COLOR_WARM_BLUE                  0x4b57db
#define COLOR_DARK_HOT_PINK              0xd90166
#define COLOR_DEEP_SEA_BLUE              0x015482
#define COLOR_CARMINE                    0x9d0216
#define COLOR_DARK_YELLOW_GREEN          0x728f02
#define COLOR_PALE_PEACH                 0xffe5ad
#define COLOR_PLUM_PURPLE                0x4e0550
#define COLOR_GOLDEN_ROD                 0xf9bc08
#define COLOR_NEON_RED                   0xff073a
#define COLOR_OLD_PINK                   0xc77986
#define COLOR_VERY_PALE_BLUE             0xd6fffe
#define COLOR_BLOOD_ORANGE               0xfe4b03
#define COLOR_GRAPEFRUIT                 0xfd5956
#define COLOR_SAND_YELLOW                0xfce166
#define COLOR_CLAY_BROWN                 0xb2713d
#define COLOR_DARK_BLUE_GREY             0x1f3b4d
#define COLOR_FLAT_GREEN                 0x699d4c
#define COLOR_LIGHT_GREEN_BLUE           0x56fca2
#define COLOR_WARM_PINK                  0xfb5581
#define COLOR_DODGER_BLUE                0x3e82fc
#define COLOR_GROSS_GREEN                0xa0bf16
#define COLOR_ICE                        0xd6fffa
#define COLOR_METALLIC_BLUE              0x4f738e
#define COLOR_PALE_SALMON                0xffb19a
#define COLOR_SAP_GREEN                  0x5c8b15
#define COLOR_ALGAE                      0x54ac68
#define COLOR_BLUEY_GREY                 0x89a0b0
#define COLOR_GREENY_GREY                0x7ea07a
#define COLOR_HIGHLIGHTER_GREEN          0x1bfc06
#define COLOR_LIGHT_LIGHT_BLUE           0xcafffb
#define COLOR_LIGHT_MINT                 0xb6ffbb
#define COLOR_RAW_UMBER                  0xa75e09
#define COLOR_VIVID_BLUE                 0x152eff
#define COLOR_DEEP_LAVENDER              0x8d5eb7
#define COLOR_DULL_TEAL                  0x5f9e8f
#define COLOR_LIGHT_GREENISH_BLUE        0x63f7b4
#define COLOR_MUD_GREEN                  0x606602
#define COLOR_PINKY                      0xfc86aa
#define COLOR_RED_WINE                   0x8c0034
#define COLOR_SHIT_GREEN                 0x758000
#define COLOR_TAN_BROWN                  0xab7e4c
#define COLOR_DARKBLUE                   0x030764
#define COLOR_ROSA                       0xfe86a4
#define COLOR_LIPSTICK                   0xd5174e
#define COLOR_PALE_MAUVE                 0xfed0fc
#define COLOR_CLARET                     0x680018
#define COLOR_DANDELION                  0xfedf08
#define COLOR_ORANGERED                  0xfe420f
#define COLOR_POOP_GREEN                 0x6f7c00
#define COLOR_RUBY                       0xca0147
#define COLOR_DARK                       0x1b2431
#define COLOR_GREENISH_TURQUOISE         0x00fbb0
#define COLOR_PASTEL_RED                 0xdb5856
#define COLOR_PISS_YELLOW                0xddd618
#define COLOR_BRIGHT_CYAN                0x41fdfe
#define COLOR_DARK_CORAL                 0xcf524e
#define COLOR_ALGAE_GREEN                0x21c36f
#define COLOR_DARKISH_RED                0xa90308
#define COLOR_REDDY_BROWN                0x6e1005
#define COLOR_BLUSH_PINK                 0xfe828c
#define COLOR_CAMOUFLAGE_GREEN           0x4b6113
#define COLOR_LAWN_GREEN                 0x4da409
#define COLOR_PUTTY                      0xbeae8a
#define COLOR_VIBRANT_BLUE               0x0339f8
#define COLOR_DARK_SAND                  0xa88f59
#define COLOR_PURPLE_BLUE                0x5d21d0
#define COLOR_SAFFRON                    0xfeb209
#define COLOR_TWILIGHT                   0x4e518b
#define COLOR_WARM_BROWN                 0x964e02
#define COLOR_BLUEGREY                   0x85a3b2
#define COLOR_BUBBLE_GUM_PINK            0xff69af
#define COLOR_DUCK_EGG_BLUE              0xc3fbf4
#define COLOR_GREENISH_CYAN              0x2afeb7
#define COLOR_PETROL                     0x005f6a
#define COLOR_ROYAL                      0x0c1793
#define COLOR_BUTTER                     0xffff81
#define COLOR_DUSTY_ORANGE               0xf0833a
#define COLOR_OFF_YELLOW                 0xf1f33f
#define COLOR_PALE_OLIVE_GREEN           0xb1d27b
#define COLOR_ORANGISH                   0xfc824a
#define COLOR_LEAF                       0x71aa34
#define COLOR_LIGHT_BLUE_GREY            0xb7c9e2
#define COLOR_DRIED_BLOOD                0x4b0101
#define COLOR_LIGHTISH_PURPLE            0xa552e6
#define COLOR_RUSTY_RED                  0xaf2f0d
#define COLOR_LAVENDER_BLUE              0x8b88f8
#define COLOR_LIGHT_GRASS_GREEN          0x9af764
#define COLOR_LIGHT_MINT_GREEN           0xa6fbb2
#define COLOR_SUNFLOWER                  0xffc512
#define COLOR_VELVET                     0x750851
#define COLOR_BRICK_ORANGE               0xc14a09
#define COLOR_LIGHTISH_RED               0xfe2f4a
#define COLOR_PURE_BLUE                  0x0203e2
#define COLOR_TWILIGHT_BLUE              0x0a437a
#define COLOR_VIOLET_RED                 0xa50055
#define COLOR_YELLOWY_BROWN              0xae8b0c
#define COLOR_CARNATION                  0xfd798f
#define COLOR_MUDDY_YELLOW               0xbfac05
#define COLOR_DARK_SEAFOAM_GREEN         0x3eaf76
#define COLOR_DEEP_ROSE                  0xc74767
#define COLOR_DUSTY_RED                  0xb9484e
#define COLOR_GREY_BLUE                  0x647d8e
#define COLOR_LEMON_LIME                 0xbffe28
#define COLOR_PURPLE_PINK                0xd725de
#define COLOR_BROWN_YELLOW               0xb29705
#define COLOR_PURPLE_BROWN               0x673a3f
#define COLOR_WISTERIA                   0xa87dc2
#define COLOR_BANANA_YELLOW              0xfafe4b
#define COLOR_LIPSTICK_RED               0xc0022f
#define COLOR_WATER_BLUE                 0x0e87cc
#define COLOR_BROWN_GREY                 0x8d8468
#define COLOR_VIBRANT_PURPLE             0xad03de
#define COLOR_BABY_GREEN                 0x8cff9e
#define COLOR_BARF_GREEN                 0x94ac02
#define COLOR_EGGSHELL_BLUE              0xc4fff7
#define COLOR_SANDY_YELLOW               0xfdee73
#define COLOR_COOL_GREEN                 0x33b864
#define COLOR_PALE                       0xfff9d0
#define COLOR_BLUE_GREY                  0x758da3
#define COLOR_HOT_MAGENTA                0xf504c9
#define COLOR_GREYBLUE                   0x77a1b5
#define COLOR_PURPLEY                    0x8756e4
#define COLOR_BABY_SHIT_GREEN            0x889717
#define COLOR_BROWNISH_PINK              0xc27e79
#define COLOR_DARK_AQUAMARINE            0x017371
#define COLOR_DIARRHEA                   0x9f8303
#define COLOR_LIGHT_MUSTARD              0xf7d560
#define COLOR_PALE_SKY_BLUE              0xbdf6fe
#define COLOR_TURTLE_GREEN               0x75b84f
#define COLOR_BRIGHT_OLIVE               0x9cbb04
#define COLOR_DARK_GREY_BLUE             0x29465b
#define COLOR_GREENY_BROWN               0x696006
#define COLOR_LEMON_GREEN                0xadf802
#define COLOR_LIGHT_PERIWINKLE           0xc1c6fc
#define COLOR_SEAWEED_GREEN              0x35ad6b
#define COLOR_SUNSHINE_YELLOW            0xfffd37
#define COLOR_UGLY_PURPLE                0xa442a0
#define COLOR_MEDIUM_PINK                0xf36196
#define COLOR_PUKE_BROWN                 0x947706
#define COLOR_VERY_LIGHT_PINK            0xfff4f2
#define COLOR_VIRIDIAN                   0x1e9167
#define COLOR_BILE                       0xb5c306
#define COLOR_FADED_YELLOW               0xfeff7f
#define COLOR_VERY_PALE_GREEN            0xcffdbc
#define COLOR_VIBRANT_GREEN              0x0add08
#define COLOR_BRIGHT_LIME                0x87fd05
#define COLOR_SPEARMINT                  0x1ef876
#define COLOR_LIGHT_AQUAMARINE           0x7bfdc7
#define COLOR_LIGHT_SAGE                 0xbcecac
#define COLOR_YELLOWGREEN                0xbbf90f
#define COLOR_BABY_POO                   0xab9004
#define COLOR_DARK_SEAFOAM               0x1fb57a
#define COLOR_DEEP_TEAL                  0x00555a
#define COLOR_HEATHER                    0xa484ac
#define COLOR_RUST_ORANGE                0xc45508
#define COLOR_DIRTY_BLUE                 0x3f829d
#define COLOR_FERN_GREEN                 0x548d44
#define COLOR_BRIGHT_LILAC               0xc95efb
#define COLOR_WEIRD_GREEN                0x3ae57f
#define COLOR_PEACOCK_BLUE               0x016795
#define COLOR_AVOCADO_GREEN              0x87a922
#define COLOR_FADED_ORANGE               0xf0944d
#define COLOR_GRAPE_PURPLE               0x5d1451
#define COLOR_HOT_GREEN                  0x25ff29
#define COLOR_LIME_YELLOW                0xd0fe1d
#define COLOR_MANGO                      0xffa62b
#define COLOR_SHAMROCK                   0x01b44c
#define COLOR_BUBBLEGUM                  0xff6cb5
#define COLOR_PURPLISH_BROWN             0x6b4247
#define COLOR_VOMIT_YELLOW               0xc7c10c
#define COLOR_PALE_CYAN                  0xb7fffa
#define COLOR_KEY_LIME                   0xaeff6e
#define COLOR_TOMATO_RED                 0xec2d01
#define COLOR_LIGHTGREEN                 0x76ff7b
#define COLOR_MERLOT                     0x730039
#define COLOR_NIGHT_BLUE                 0x040348
#define COLOR_PURPLEISH_PINK             0xdf4ec8
#define COLOR_APPLE                      0x6ecb3c
#define COLOR_BABY_POOP_GREEN            0x8f9805
#define COLOR_GREEN_APPLE                0x5edc1f
#define COLOR_HELIOTROPE                 0xd94ff5
#define COLOR_YELLOW_GREEN               0xc8fd3d
#define COLOR_ALMOST_BLACK               0x070d0d
#define COLOR_COOL_BLUE                  0x4984b8
#define COLOR_LEAFY_GREEN                0x51b73b
#define COLOR_MUSTARD_BROWN              0xac7e04
#define COLOR_DUSK                       0x4e5481
#define COLOR_DULL_BROWN                 0x876e4b
#define COLOR_FROG_GREEN                 0x58bc08
#define COLOR_VIVID_GREEN                0x2fef10
#define COLOR_BRIGHT_LIGHT_GREEN         0x2dfe54
#define COLOR_FLURO_GREEN                0x0aff02
#define COLOR_KIWI                       0x9cef43
#define COLOR_SEAWEED                    0x18d17b
#define COLOR_NAVY_GREEN                 0x35530a
#define COLOR_ULTRAMARINE_BLUE           0x1805db
#define COLOR_IRIS                       0x6258c4
#define COLOR_PASTEL_ORANGE              0xff964f
#define COLOR_YELLOWISH_ORANGE           0xffab0f
#define COLOR_PERRYWINKLE                0x8f8ce7
#define COLOR_TEALISH                    0x24bca8
#define COLOR_DARK_PLUM                  0x3f012c
#define COLOR_PEAR                       0xcbf85f
#define COLOR_PINKISH_ORANGE             0xff724c
#define COLOR_MIDNIGHT_PURPLE            0x280137
#define COLOR_LIGHT_URPLE                0xb36ff6
#define COLOR_DARK_MINT                  0x48c072
#define COLOR_GREENISH_TAN               0xbccb7a
#define COLOR_LIGHT_BURGUNDY             0xa8415b
#define COLOR_TURQUOISE_BLUE             0x06b1c4
#define COLOR_UGLY_PINK                  0xcd7584
#define COLOR_SANDY                      0xf1da7a
#define COLOR_ELECTRIC_PINK              0xff0490
#define COLOR_MUTED_PURPLE               0x805b87
#define COLOR_MID_GREEN                  0x50a747
#define COLOR_GREYISH                    0xa8a495
#define COLOR_NEON_YELLOW                0xcfff04
#define COLOR_BANANA                     0xffff7e
#define COLOR_CARNATION_PINK             0xff7fa7
#define COLOR_TOMATO                     0xef4026
#define COLOR_SEA                        0x3c9992
#define COLOR_MUDDY_BROWN                0x886806
#define COLOR_TURQUOISE_GREEN            0x04f489
#define COLOR_BUFF                       0xfef69e
#define COLOR_FAWN                       0xcfaf7b
#define COLOR_MUTED_BLUE                 0x3b719f
#define COLOR_PALE_ROSE                  0xfdc1c5
#define COLOR_DARK_MINT_GREEN            0x20c073
#define COLOR_AMETHYST                   0x9b5fc0
#define COLOR_BLUE_GREEN                 0x0f9b8e
#define COLOR_CHESTNUT                   0x742802
#define COLOR_SICK_GREEN                 0x9db92c
#define COLOR_PEA                        0xa4bf20
#define COLOR_RUSTY_ORANGE               0xcd5909
#define COLOR_STONE                      0xada587
#define COLOR_ROSE_RED                   0xbe013c
#define COLOR_PALE_AQUA                  0xb8ffeb
#define COLOR_DEEP_ORANGE                0xdc4d01
#define COLOR_EARTH                      0xa2653e
#define COLOR_MOSSY_GREEN                0x638b27
#define COLOR_GRASSY_GREEN               0x419c03
#define COLOR_PALE_LIME_GREEN            0xb1ff65
#define COLOR_LIGHT_GREY_BLUE            0x9dbcd4
#define COLOR_PALE_GREY                  0xfdfdfe
#define COLOR_ASPARAGUS                  0x77ab56
#define COLOR_BLUEBERRY                  0x464196
#define COLOR_PURPLE_RED                 0x990147
#define COLOR_PALE_LIME                  0xbefd73
#define COLOR_GREENISH_TEAL              0x32bf84
#define COLOR_CARAMEL                    0xaf6f09
#define COLOR_DEEP_MAGENTA               0xa0025c
#define COLOR_LIGHT_PEACH                0xffd8b1
#define COLOR_MILK_CHOCOLATE             0x7f4e1e
#define COLOR_OCHER                      0xbf9b0c
#define COLOR_OFF_GREEN                  0x6ba353
#define COLOR_PURPLY_PINK                0xf075e6
#define COLOR_LIGHTBLUE                  0x7bc8f6
#define COLOR_DUSKY_BLUE                 0x475f94
#define COLOR_GOLDEN                     0xf5bf03
#define COLOR_LIGHT_BEIGE                0xfffeb6
#define COLOR_BUTTER_YELLOW              0xfffd74
#define COLOR_DUSKY_PURPLE               0x895b7b
#define COLOR_FRENCH_BLUE                0x436bad
#define COLOR_UGLY_YELLOW                0xd0c101
#define COLOR_GREENY_YELLOW              0xc6f808
#define COLOR_ORANGISH_RED               0xf43605
#define COLOR_SHAMROCK_GREEN             0x02c14d
#define COLOR_ORANGISH_BROWN             0xb25f03
#define COLOR_TREE_GREEN                 0x2a7e19
#define COLOR_DEEP_VIOLET                0x490648
#define COLOR_GUNMETAL                   0x536267
#define COLOR_BLUE_PURPLE                0x5a06ef
#define COLOR_CHERRY                     0xcf0234
#define COLOR_SANDY_BROWN                0xc4a661
#define COLOR_WARM_GREY                  0x978a84
#define COLOR_DARK_INDIGO                0x1f0954
#define COLOR_MIDNIGHT                   0x03012d
#define COLOR_BLUEY_GREEN                0x2bb179
#define COLOR_GREY_PINK                  0xc3909b
#define COLOR_SOFT_PURPLE                0xa66fb5
#define COLOR_BLOOD                      0x770001
#define COLOR_BROWN_RED                  0x922b05
#define COLOR_MEDIUM_GREY                0x7d7f7c
#define COLOR_BERRY                      0x990f4b
#define COLOR_POO                        0x8f7303
#define COLOR_PURPLEY_PINK               0xc83cb9
#define COLOR_LIGHT_SALMON               0xfea993
#define COLOR_SNOT                       0xacbb0d
#define COLOR_EASTER_PURPLE              0xc071fe
#define COLOR_LIGHT_YELLOW_GREEN         0xccfd7f
#define COLOR_DARK_NAVY_BLUE             0x00022e
#define COLOR_DRAB                       0x828344
#define COLOR_LIGHT_ROSE                 0xffc5cb
#define COLOR_ROUGE                      0xab1239
#define COLOR_PURPLISH_RED               0xb0054b
#define COLOR_SLIME_GREEN                0x99cc04
#define COLOR_BABY_POOP                  0x937c00
#define COLOR_IRISH_GREEN                0x019529
#define COLOR_PINK_PURPLE                0xef1de7
#define COLOR_DARK_NAVY                  0x000435
#define COLOR_GREENY_BLUE                0x42b395
#define COLOR_LIGHT_PLUM                 0x9d5783
#define COLOR_PINKISH_GREY               0xc8aca9
#define COLOR_DIRTY_ORANGE               0xc87606
#define COLOR_RUST_RED                   0xaa2704
#define COLOR_PALE_LILAC                 0xe4cbff
#define COLOR_ORANGEY_RED                0xfa4224
#define COLOR_PRIMARY_BLUE               0x0804f9
#define COLOR_KERMIT_GREEN               0x5cb200
#define COLOR_BROWNISH_PURPLE            0x76424e
#define COLOR_MURKY_GREEN                0x6c7a0e
#define COLOR_WHEAT                      0xfbdd7e
#define COLOR_VERY_DARK_PURPLE           0x2a0134
#define COLOR_BOTTLE_GREEN               0x044a05
#define COLOR_WATERMELON                 0xfd4659
#define COLOR_DEEP_SKY_BLUE              0x0d75f8
#define COLOR_FIRE_ENGINE_RED            0xfe0002
#define COLOR_YELLOW_OCHRE               0xcb9d06
#define COLOR_PUMPKIN_ORANGE             0xfb7d07
#define COLOR_PALE_OLIVE                 0xb9cc81
#define COLOR_LIGHT_LILAC                0xedc8ff
#define COLOR_LIGHTISH_GREEN             0x61e160
#define COLOR_CAROLINA_BLUE              0x8ab8fe
#define COLOR_MULBERRY                   0x920a4e
#define COLOR_SHOCKING_PINK              0xfe02a2
#define COLOR_AUBURN                     0x9a3001
#define COLOR_BRIGHT_LIME_GREEN          0x65fe08
#define COLOR_CELADON                    0xbefdb7
#define COLOR_PINKISH_BROWN              0xb17261
#define COLOR_POO_BROWN                  0x885f01
#define COLOR_BRIGHT_SKY_BLUE            0x02ccfe
#define COLOR_CELERY                     0xc1fd95
#define COLOR_DIRT_BROWN                 0x836539
#define COLOR_STRAWBERRY                 0xfb2943
#define COLOR_DARK_LIME                  0x84b701
#define COLOR_COPPER                     0xb66325
#define COLOR_MEDIUM_BROWN               0x7f5112
#define COLOR_MUTED_GREEN                0x5fa052
#define COLOR_ROBINS_EGG                 0x6dedfd
#define COLOR_BRIGHT_AQUA                0x0bf9ea
#define COLOR_BRIGHT_LAVENDER            0xc760ff
#define COLOR_IVORY                      0xffffcb
#define COLOR_VERY_LIGHT_PURPLE          0xf6cefc
#define COLOR_LIGHT_NAVY                 0x155084
#define COLOR_PINK_RED                   0xf5054f
#define COLOR_OLIVE_BROWN                0x645403
#define COLOR_POOP_BROWN                 0x7a5901
#define COLOR_MUSTARD_GREEN              0xa8b504
#define COLOR_OCEAN_GREEN                0x3d9973
#define COLOR_VERY_DARK_BLUE             0x000133
#define COLOR_DUSTY_GREEN                0x76a973
#define COLOR_LIGHT_NAVY_BLUE            0x2e5a88
#define COLOR_MINTY_GREEN                0x0bf77d
#define COLOR_ADOBE                      0xbd6c48
#define COLOR_BARNEY                     0xac1db8
#define COLOR_JADE_GREEN                 0x2baf6a
#define COLOR_BRIGHT_LIGHT_BLUE          0x26f7fd
#define COLOR_LIGHT_LIME                 0xaefd6c
#define COLOR_DARK_KHAKI                 0x9b8f55
#define COLOR_ORANGE_YELLOW              0xffad01
#define COLOR_OCRE                       0xc69c04
#define COLOR_MAIZE                      0xf4d054
#define COLOR_FADED_PINK                 0xde9dac
#define COLOR_BRITISH_RACING_GREEN       0x05480d
#define COLOR_SANDSTONE                  0xc9ae74
#define COLOR_MUD_BROWN                  0x60460f
#define COLOR_LIGHT_SEA_GREEN            0x98f6b0
#define COLOR_ROBIN_EGG_BLUE             0x8af1fe
#define COLOR_AQUA_MARINE                0x2ee8bb
#define COLOR_DARK_SEA_GREEN             0x11875d
#define COLOR_SOFT_PINK                  0xfdb0c0
#define COLOR_ORANGEY_BROWN              0xb16002
#define COLOR_CHERRY_RED                 0xf7022a
#define COLOR_BURNT_YELLOW               0xd5ab09
#define COLOR_BROWNISH_GREY              0x86775f
#define COLOR_CAMEL                      0xc69f59
#define COLOR_PURPLISH_GREY              0x7a687f
#define COLOR_MARINE                     0x042e60
#define COLOR_GREYISH_PINK               0xc88d94
#define COLOR_PALE_TURQUOISE             0xa5fbd5
#define COLOR_PASTEL_YELLOW              0xfffe71
#define COLOR_BLUEY_PURPLE               0x6241c7
#define COLOR_CANARY_YELLOW              0xfffe40
#define COLOR_FADED_RED                  0xd3494e
#define COLOR_SEPIA                      0x985e2b
#define COLOR_COFFEE                     0xa6814c
#define COLOR_BRIGHT_MAGENTA             0xff08e8
#define COLOR_MOCHA                      0x9d7651
#define COLOR_ECRU                       0xfeffca
#define COLOR_PURPLEISH                  0x98568d
#define COLOR_CRANBERRY                  0x9e003a
#define COLOR_DARKISH_GREEN              0x287c37
#define COLOR_BROWN_ORANGE               0xb96902
#define COLOR_DUSKY_ROSE                 0xba6873
#define COLOR_MELON                      0xff7855
#define COLOR_SICKLY_GREEN               0x94b21c
#define COLOR_SILVER                     0xc5c9c7
#define COLOR_PURPLY_BLUE                0x661aee
#define COLOR_PURPLEISH_BLUE             0x6140ef
#define COLOR_HOSPITAL_GREEN             0x9be5aa
#define COLOR_SHIT_BROWN                 0x7b5804
#define COLOR_MID_BLUE                   0x276ab3
#define COLOR_AMBER                      0xfeb308
#define COLOR_EASTER_GREEN               0x8cfd7e
#define COLOR_SOFT_BLUE                  0x6488ea
#define COLOR_CERULEAN_BLUE              0x056eee
#define COLOR_GOLDEN_BROWN               0xb27a01
#define COLOR_BRIGHT_TURQUOISE           0x0ffef9
#define COLOR_RED_PINK                   0xfa2a55
#define COLOR_RED_PURPLE                 0x820747
#define COLOR_GREYISH_BROWN              0x7a6a4f
#define COLOR_VERMILLION                 0xf4320c
#define COLOR_RUSSET                     0xa13905
#define COLOR_STEEL_GREY                 0x6f828a
#define COLOR_LIGHTER_PURPLE             0xa55af4
#define COLOR_BRIGHT_VIOLET              0xad0afd
#define COLOR_PRUSSIAN_BLUE              0x004577
#define COLOR_SLATE_GREEN                0x658d6d
#define COLOR_DIRTY_PINK                 0xca7b80
#define COLOR_DARK_BLUE_GREEN            0x005249
#define COLOR_PINE                       0x2b5d34
#define COLOR_YELLOWY_GREEN              0xbff128
#define COLOR_DARK_GOLD                  0xb59410
#define COLOR_BLUISH                     0x2976bb
#define COLOR_DARKISH_BLUE               0x014182
#define COLOR_DULL_RED                   0xbb3f3f
#define COLOR_PINKY_RED                  0xfc2647
#define COLOR_BRONZE                     0xa87900
#define COLOR_PALE_TEAL                  0x82cbb2
#define COLOR_MILITARY_GREEN             0x667c3e
#define COLOR_BARBIE_PINK                0xfe46a5
#define COLOR_BUBBLEGUM_PINK             0xfe83cc
#define COLOR_PEA_SOUP_GREEN             0x94a617
#define COLOR_DARK_MUSTARD               0xa88905
#define COLOR_SHIT                       0x7f5f00
#define COLOR_MEDIUM_PURPLE              0x9e43a2
#define COLOR_VERY_DARK_GREEN            0x062e03
#define COLOR_DIRT                       0x8a6e45
#define COLOR_DUSKY_PINK                 0xcc7a8b
#define COLOR_RED_VIOLET                 0x9e0168
#define COLOR_LEMON_YELLOW               0xfdff38
#define COLOR_PISTACHIO                  0xc0fa8b
#define COLOR_DULL_YELLOW                0xeedc5b
#define COLOR_DARK_LIME_GREEN            0x7ebd01
#define COLOR_DENIM_BLUE                 0x3b5b92
#define COLOR_TEAL_BLUE                  0x01889f
#define COLOR_LIGHTISH_BLUE              0x3d7afd
#define COLOR_PURPLEY_BLUE               0x5f34e7
#define COLOR_LIGHT_INDIGO               0x6d5acf
#define COLOR_SWAMP_GREEN                0x748500
#define COLOR_BROWN_GREEN                0x706c11
#define COLOR_DARK_MAROON                0x3c0008
#define COLOR_HOT_PURPLE                 0xcb00f5
#define COLOR_DARK_FOREST_GREEN          0x002d04
#define COLOR_FADED_BLUE                 0x658cbb
#define COLOR_DRAB_GREEN                 0x749551
#define COLOR_LIGHT_LIME_GREEN           0xb9ff66
#define COLOR_SNOT_GREEN                 0x9dc100
#define COLOR_YELLOWISH                  0xfaee66
#define COLOR_LIGHT_BLUE_GREEN           0x7efbb3
#define COLOR_BORDEAUX                   0x7b002c
#define COLOR_LIGHT_MAUVE                0xc292a1
#define COLOR_OCEAN                      0x017b92
#define COLOR_MARIGOLD                   0xfcc006
#define COLOR_MUDDY_GREEN                0x657432
#define COLOR_DULL_ORANGE                0xd8863b
#define COLOR_STEEL                      0x738595
#define COLOR_ELECTRIC_PURPLE            0xaa23ff
#define COLOR_FLUORESCENT_GREEN          0x08ff08
#define COLOR_YELLOWISH_BROWN            0x9b7a01
#define COLOR_BLUSH                      0xf29e8e
#define COLOR_SOFT_GREEN                 0x6fc276
#define COLOR_BRIGHT_ORANGE              0xff5b00
#define COLOR_LEMON                      0xfdff52
#define COLOR_PURPLE_GREY                0x866f85
#define COLOR_ACID_GREEN                 0x8ffe09
#define COLOR_PALE_LAVENDER              0xeecffe
#define COLOR_VIOLET_BLUE                0x510ac9
#define COLOR_LIGHT_FOREST_GREEN         0x4f9153
#define COLOR_BURNT_RED                  0x9f2305
#define COLOR_KHAKI_GREEN                0x728639
#define COLOR_CERISE                     0xde0c62
#define COLOR_FADED_PURPLE               0x916e99
#define COLOR_APRICOT                    0xffb16d
#define COLOR_DARK_OLIVE_GREEN           0x3c4d03
#define COLOR_GREY_BROWN                 0x7f7053
#define COLOR_GREEN_GREY                 0x77926f
#define COLOR_TRUE_BLUE                  0x010fcc
#define COLOR_PALE_VIOLET                0xceaefa
#define COLOR_PERIWINKLE_BLUE            0x8f99fb
#define COLOR_LIGHT_SKY_BLUE             0xc6fcff
#define COLOR_BLURPLE                    0x5539cc
#define COLOR_GREEN_BROWN                0x544e03
#define COLOR_BLUEGREEN                  0x017a79
#define COLOR_BRIGHT_TEAL                0x01f9c6
#define COLOR_BROWNISH_YELLOW            0xc9b003
#define COLOR_PEA_SOUP                   0x929901
#define COLOR_FOREST                     0x0b5509
#define COLOR_BARNEY_PURPLE              0xa00498
#define COLOR_ULTRAMARINE                0x2000b1
#define COLOR_PURPLISH                   0x94568c
#define COLOR_PUKE_YELLOW                0xc2be0e
#define COLOR_BLUISH_GREY                0x748b97
#define COLOR_DARK_PERIWINKLE            0x665fd1
#define COLOR_DARK_LILAC                 0x9c6da5
#define COLOR_REDDISH                    0xc44240
#define COLOR_LIGHT_MAROON               0xa24857
#define COLOR_DUSTY_PURPLE               0x825f87
#define COLOR_TERRA_COTTA                0xc9643b
#define COLOR_AVOCADO                    0x90b134
#define COLOR_MARINE_BLUE                0x01386a
#define COLOR_TEAL_GREEN                 0x25a36f
#define COLOR_SLATE_GREY                 0x59656d
#define COLOR_LIGHTER_GREEN              0x75fd63
#define COLOR_ELECTRIC_GREEN             0x21fc0d
#define COLOR_DUSTY_BLUE                 0x5a86ad
#define COLOR_GOLDEN_YELLOW              0xfec615
#define COLOR_BRIGHT_YELLOW              0xfffd01
#define COLOR_LIGHT_LAVENDER             0xdfc5fe
#define COLOR_UMBER                      0xb26400
#define COLOR_POOP                       0x7f5e00
#define COLOR_DARK_PEACH                 0xde7e5d
#define COLOR_JUNGLE_GREEN               0x048243
#define COLOR_EGGSHELL                   0xffffd4
#define COLOR_DENIM                      0x3b638c
#define COLOR_YELLOW_BROWN               0xb79400
#define COLOR_DULL_PURPLE                0x84597e
#define COLOR_CHOCOLATE_BROWN            0x411900
#define COLOR_WINE_RED                   0x7b0323
#define COLOR_NEON_BLUE                  0x04d9ff
#define COLOR_DIRTY_GREEN                0x667e2c
#define COLOR_LIGHT_TAN                  0xfbeeac
#define COLOR_ICE_BLUE                   0xd7fffe
#define COLOR_CADET_BLUE                 0x4e7496
#define COLOR_DARK_MAUVE                 0x874c62
#define COLOR_VERY_LIGHT_BLUE            0xd5ffff
#define COLOR_GREY_PURPLE                0x826d8c
#define COLOR_PASTEL_PINK                0xffbacd
#define COLOR_VERY_LIGHT_GREEN           0xd1ffbd
#define COLOR_DARK_SKY_BLUE              0x448ee4
#define COLOR_EVERGREEN                  0x05472a
#define COLOR_DULL_PINK                  0xd5869d
#define COLOR_AUBERGINE                  0x3d0734
#define COLOR_MAHOGANY                   0x4a0100
#define COLOR_REDDISH_ORANGE             0xf8481c
#define COLOR_DEEP_GREEN                 0x02590f
#define COLOR_VOMIT_GREEN                0x89a203
//#define COLOR_PURPLE_PINK              0xe03fd8
#define COLOR_DUSTY_PINK                 0xd58a94
#define COLOR_FADED_GREEN                0x7bb274
#define COLOR_CAMO_GREEN                 0x526525
#define COLOR_PINKY_PURPLE               0xc94cbe
//#define COLOR_PINK_PURPLE              0xdb4bda
#define COLOR_BROWNISH_RED               0x9e3623
#define COLOR_DARK_ROSE                  0xb5485d
#define COLOR_MUD                        0x735c12
#define COLOR_BROWNISH                   0x9c6d57
#define COLOR_EMERALD_GREEN              0x028f1e
#define COLOR_PALE_BROWN                 0xb1916e
#define COLOR_DULL_BLUE                  0x49759c
#define COLOR_BURNT_UMBER                0xa0450e
#define COLOR_MEDIUM_GREEN               0x39ad48
#define COLOR_CLAY                       0xb66a50
#define COLOR_LIGHT_AQUA                 0x8cffdb
#define COLOR_LIGHT_OLIVE_GREEN          0xa4be5c
#define COLOR_BROWNISH_ORANGE            0xcb7723
#define COLOR_DARK_AQUA                  0x05696b
#define COLOR_PURPLISH_PINK              0xce5dae
#define COLOR_DARK_SALMON                0xc85a53
#define COLOR_GREENISH_GREY              0x96ae8d
#define COLOR_JADE                       0x1fa774
#define COLOR_UGLY_GREEN                 0x7a9703
#define COLOR_DARK_BEIGE                 0xac9362
#define COLOR_EMERALD                    0x01a049
#define COLOR_PALE_RED                   0xd9544d
#define COLOR_LIGHT_MAGENTA              0xfa5ff7
#define COLOR_SKY                        0x82cafc
#define COLOR_LIGHT_CYAN                 0xacfffc
#define COLOR_YELLOW_ORANGE              0xfcb001
#define COLOR_REDDISH_PURPLE             0x910951
#define COLOR_REDDISH_PINK               0xfe2c54
#define COLOR_ORCHID                     0xc875c4
#define COLOR_DIRTY_YELLOW               0xcdc50a
#define COLOR_ORANGE_RED                 0xfd411e
#define COLOR_DEEP_RED                   0x9a0200
#define COLOR_ORANGE_BROWN               0xbe6400
#define COLOR_COBALT_BLUE                0x030aa7
#define COLOR_NEON_PINK                  0xfe019a
#define COLOR_ROSE_PINK                  0xf7879a
#define COLOR_GREYISH_PURPLE             0x887191
#define COLOR_RASPBERRY                  0xb00149
#define COLOR_AQUA_GREEN                 0x12e193
#define COLOR_SALMON_PINK                0xfe7b7c
#define COLOR_TANGERINE                  0xff9408
#define COLOR_BROWNISH_GREEN             0x6a6e09
#define COLOR_RED_BROWN                  0x8b2e16
#define COLOR_GREENISH_BROWN             0x696112
#define COLOR_PUMPKIN                    0xe17701
#define COLOR_PINE_GREEN                 0x0a481e
#define COLOR_CHARCOAL                   0x343837
#define COLOR_BABY_PINK                  0xffb7ce
#define COLOR_CORNFLOWER                 0x6a79f7
#define COLOR_BLUE_VIOLET                0x5d06e9
#define COLOR_CHOCOLATE                  0x3d1c02
#define COLOR_GREYISH_GREEN              0x82a67d
#define COLOR_SCARLET                    0xbe0119
//#define COLOR_GREEN_YELLOW             0xc9ff27
#define COLOR_DARK_OLIVE                 0x373e02
#define COLOR_SIENNA                     0xa9561e
#define COLOR_PASTEL_PURPLE              0xcaa0ff
#define COLOR_TERRACOTTA                 0xca6641
#define COLOR_AQUA_BLUE                  0x02d8e9
#define COLOR_SAGE_GREEN                 0x88b378
#define COLOR_BLOOD_RED                  0x980002
#define COLOR_DEEP_PINK                  0xcb0162
#define COLOR_GRASS                      0x5cac2d
#define COLOR_MOSS                       0x769958
#define COLOR_PASTEL_BLUE                0xa2bffe
#define COLOR_BLUISH_GREEN               0x10a674
//#define COLOR_GREEN_BLUE               0x06b48b
#define COLOR_DARK_TAN                   0xaf884a
#define COLOR_GREENISH_BLUE              0x0b8b87
#define COLOR_PALE_ORANGE                0xffa756
#define COLOR_VOMIT                      0xa2a415
#define COLOR_FORREST_GREEN              0x154406
#define COLOR_DARK_LAVENDER              0x856798
#define COLOR_DARK_VIOLET                0x34013f
//#define COLOR_PURPLE_BLUE              0x632de9
#define COLOR_DARK_CYAN                  0x0a888a
#define COLOR_OLIVE_DRAB                 0x6f7632
#define COLOR_PINKISH                    0xd46a7e
#define COLOR_COBALT                     0x1e488f
#define COLOR_NEON_PURPLE                0xbc13fe
#define COLOR_LIGHT_TURQUOISE            0x7ef4cc
#define COLOR_APPLE_GREEN                0x76cd26
#define COLOR_DULL_GREEN                 0x74a662
#define COLOR_WINE                       0x80013f
#define COLOR_POWDER_BLUE                0xb1d1fc
#define COLOR_OFF_WHITE                  0xffffe4
#define COLOR_ELECTRIC_BLUE              0x0652ff
#define COLOR_DARK_TURQUOISE             0x045c5a
//#define COLOR_BLUE_PURPLE              0x5729ce
#define COLOR_AZURE                      0x069af3
#define COLOR_BRIGHT_RED                 0xff000d
#define COLOR_PINKISH_RED                0xf10c45
#define COLOR_CORNFLOWER_BLUE            0x5170d7
#define COLOR_LIGHT_OLIVE                0xacbf69
#define COLOR_GRAPE                      0x6c3461
#define COLOR_GREYISH_BLUE               0x5e819d
#define COLOR_PURPLISH_BLUE              0x601ef9
#define COLOR_YELLOWISH_GREEN            0xb0dd16
#define COLOR_GREENISH_YELLOW            0xcdfd02
#define COLOR_MEDIUM_BLUE                0x2c6fbb
#define COLOR_DUSTY_ROSE                 0xc0737a
#define COLOR_LIGHT_VIOLET               0xd6b4fc
#define COLOR_MIDNIGHT_BLUE              0x020035
#define COLOR_BLUISH_PURPLE              0x703be7
#define COLOR_RED_ORANGE                 0xfd3c06
#define COLOR_DARK_MAGENTA               0x960056
#define COLOR_GREENISH                   0x40a368
#define COLOR_OCEAN_BLUE                 0x03719c
#define COLOR_CORAL                      0xfc5a50
#define COLOR_CREAM                      0xffffc2
#define COLOR_REDDISH_BROWN              0x7f2b0a
#define COLOR_BURNT_SIENNA               0xb04e0f
#define COLOR_BRICK                      0xa03623
#define COLOR_SAGE                       0x87ae73
//#define COLOR_GREY_GREEN               0x789b73
#define COLOR_WHITE                      0xffffff
#define COLOR_ROBINS_EGG_BLUE            0x98eff9
#define COLOR_MOSS_GREEN                 0x658b38
#define COLOR_STEEL_BLUE                 0x5a7d9a
#define COLOR_EGGPLANT                   0x380835
#define COLOR_LIGHT_YELLOW               0xfffe7a
#define COLOR_LEAF_GREEN                 0x5ca904
#define COLOR_LIGHT_GREY                 0xd8dcd6
#define COLOR_PUKE                       0xa5a502
#define COLOR_PINKISH_PURPLE             0xd648d7
#define COLOR_SEA_BLUE                   0x047495
#define COLOR_PALE_PURPLE                0xb790d4
#define COLOR_SLATE_BLUE                 0x5b7c99
//#define COLOR_BLUE_GREY                0x607c8e
#define COLOR_HUNTER_GREEN               0x0b4008
#define COLOR_FUCHSIA                    0xed0dd9
#define COLOR_CRIMSON                    0x8c000f
#define COLOR_PALE_YELLOW                0xffff84
#define COLOR_OCHRE                      0xbf9005
#define COLOR_MUSTARD_YELLOW             0xd2bd0a
#define COLOR_LIGHT_RED                  0xff474c
#define COLOR_CERULEAN                   0x0485d1
#define COLOR_PALE_PINK                  0xffcfdc
#define COLOR_DEEP_BLUE                  0x040273
#define COLOR_RUST                       0xa83c09
#define COLOR_LIGHT_TEAL                 0x90e4c1
#define COLOR_SLATE                      0x516572
#define COLOR_GOLDENROD                  0xfac205
#define COLOR_DARK_YELLOW                0xd5b60a
#define COLOR_DARK_GREY                  0x363737
#define COLOR_ARMY_GREEN                 0x4b5d16
//#define COLOR_GREY_BLUE                0x6b8ba4
#define COLOR_SEAFOAM                    0x80f9ad
#define COLOR_PUCE                       0xa57e52
#define COLOR_SPRING_GREEN               0xa9f971
#define COLOR_DARK_ORANGE                0xc65102
#define COLOR_SAND                       0xe2ca76
#define COLOR_PASTEL_GREEN               0xb0ff9d
#define COLOR_MINT                       0x9ffeb0
#define COLOR_LIGHT_ORANGE               0xfdaa48
#define COLOR_BRIGHT_PINK                0xfe01b1
#define COLOR_CHARTREUSE                 0xc1f80a
#define COLOR_DEEP_PURPLE                0x36013f
#define COLOR_DARK_BROWN                 0x341c02
#define COLOR_TAUPE                      0xb9a281
#define COLOR_PEA_GREEN                  0x8eab12
#define COLOR_PUKE_GREEN                 0x9aae07
#define COLOR_KELLY_GREEN                0x02ab2e
#define COLOR_SEAFOAM_GREEN              0x7af9ab
//#define COLOR_BLUE_GREEN               0x137e6d
#define COLOR_KHAKI                      0xaaa662
#define COLOR_BURGUNDY                   0x610023
#define COLOR_DARK_TEAL                  0x014d4e
#define COLOR_BRICK_RED                  0x8f1402
#define COLOR_ROYAL_PURPLE               0x4b006e
#define COLOR_PLUM                       0x580f41
#define COLOR_MINT_GREEN                 0x8fff9f
#define COLOR_GOLD                       0xdbb40c
#define COLOR_BABY_BLUE                  0xa2cffe
//#define COLOR_YELLOW_GREEN             0xc0fb2d
#define COLOR_BRIGHT_PURPLE              0xbe03fd
#define COLOR_DARK_RED                   0x840000
#define COLOR_PALE_BLUE                  0xd0fefe
#define COLOR_GRASS_GREEN                0x3f9b0b
#define COLOR_NAVY                       0x01153e
#define COLOR_AQUAMARINE                 0x04d8b2
#define COLOR_BURNT_ORANGE               0xc04e01
#define COLOR_NEON_GREEN                 0x0cff0c
#define COLOR_BRIGHT_BLUE                0x0165fc
#define COLOR_ROSE                       0xcf6275
#define COLOR_LIGHT_PINK                 0xffd1df
#define COLOR_MUSTARD                    0xceb301
#define COLOR_INDIGO                     0x380282
#define COLOR_LIME                       0xaaff32
#define COLOR_SEA_GREEN                  0x53fca1
#define COLOR_PERIWINKLE                 0x8e82fe
#define COLOR_DARK_PINK                  0xcb416b
#define COLOR_OLIVE_GREEN                0x677a04
#define COLOR_PEACH                      0xffb07c
#define COLOR_PALE_GREEN                 0xc7fdb5
#define COLOR_LIGHT_BROWN                0xad8150
#define COLOR_HOT_PINK                   0xff028d
#define COLOR_BLACK                      0x000000
#define COLOR_LILAC                      0xcea2fd
#define COLOR_NAVY_BLUE                  0x001146
#define COLOR_ROYAL_BLUE                 0x0504aa
#define COLOR_BEIGE                      0xe6daa6
#define COLOR_SALMON                     0xff796c
#define COLOR_OLIVE                      0x6e750e
#define COLOR_MAROON                     0x650021
#define COLOR_BRIGHT_GREEN               0x01ff07
#define COLOR_DARK_PURPLE                0x35063e
#define COLOR_MAUVE                      0xae7181
#define COLOR_FOREST_GREEN               0x06470c
#define COLOR_AQUA                       0x13eac9
#define COLOR_CYAN                       0x00ffff
#define COLOR_TAN                        0xd1b26f
#define COLOR_DARK_BLUE                  0x00035b
#define COLOR_LAVENDER                   0xc79fef
#define COLOR_TURQUOISE                  0x06c2ac
#define COLOR_DARK_GREEN                 0x033500
#define COLOR_VIOLET                     0x9a0eea
#define COLOR_LIGHT_PURPLE               0xbf77f6
#define COLOR_LIME_GREEN                 0x89fe05
#define COLOR_GREY                       0x929591
#define COLOR_SKY_BLUE                   0x75bbfd
#define COLOR_YELLOW                     0xffff14
#define COLOR_MAGENTA                    0xc20078
#define COLOR_LIGHT_GREEN                0x96f97b
#define COLOR_ORANGE                     0xf97306
#define COLOR_TEAL                       0x029386
#define COLOR_LIGHT_BLUE                 0x95d0fc
#define COLOR_RED                        0xe50000
#define COLOR_BROWN                      0x653700
#define COLOR_PINK                       0xff81c0
#define COLOR_BLUE                       0x0343df
#define COLOR_GREEN                      0x15b01a
#define COLOR_PURPLE                     0x7e1e9c
